### ISSUE TITLE
Multiple viewmodels per page

### ISSUE THREAD

**Issue by neilyoung** [SteveSanderson/generator-ko#14]
Hi Steve,

not an issue, just wondering, how to achieve multiple viewmodels per page w/o breaking the clear pattern. 

Thanks for that wonderful lesson regarding "best ko practices"

**Comment by bikeshedder** [comment]
I'm curious what you mean by "clear" pattern? For multiple view models per page I simply used `ko.applyBindings` with a second parameter specifying the element: `ko.applyBindings(viewModel, element)`

Nowadays I often find myself using a master view model that contains the two sub models and use the `with` statement in the HTML.

```javascript
var model = {
    a: new SubModelA(),
    b: new SubModelB()
};
ko.applyBindings(model);
```

```html
<div data-bind="with: a">
    ...
</div>
<div data-bind="with: b">
    ...
</div>
```

That also makes it possible to store the two sub models in an observable that is assigned when the sub models are needed and/or ready:

```javascript
var model = {
    a: ko.observable(null),
    b: ko.observable(null)
};
ko.applyBindings(model);
// whenever the a or b submodels are ready simply assign them:
model.a(new SubModelA());
model.b(new SubModelB());
```

I hope I'm not answering in a completely different direction as I don't know what you mean by "clear" pattern. :wink:

**Comment by neilyoung** [comment]
Yes, sorry for not being specific enough. This post is pretty old and I can't really remember what hiccup I had with this. Thanks for explanations.
