### ISSUE TITLE
yeoman with knockout spits .js files with typescript content

### ISSUE THREAD

**Issue by kramer888** [SteveSanderson/generator-ko#21]
I used yeoman a few months ago when I started to build an SPA app with knockout. It scaffold the project and also asked me before if I want a javascript or typescript. Now when I'm using the same command, I get the initial questions from yeoman i.e. name of project, unit tests etc' but no if I want a javascript or typescript. On top of that the project that I get is .js files with typescript inside

**Comment by oacevedo** [comment]
https://github.com/SteveSanderson/generator-ko/issues/18

**Comment by SteveSanderson** [comment]
@oacevedo is correct - closing
