### ISSUE TITLE
JS Script Cache Invalidation

### ISSUE THREAD

**Issue by carlosagsmendes** [SteveSanderson/generator-ko#9]
@SteveSanderson, would you consider adding support for JS script cache invalidation?

I was wondering if instead of calculating the MD5 using the filename in the 'js' task:

```javascript
gulp.task('js', function () {
    return rjs(requireJsOptimizerConfig)
        .pipe(uglify({ preserveComments: 'some' }))
        .pipe(md5())
        .pipe(gulp.dest('./dist/'));
});
```

we could do something similar using the file contents for hashing.

Thanks in advance

**Comment by neelabhg** [comment]
@carlosagsmendes Yeoman's generator-gulp-webapp has a [receipe page for setting up asset revisioning](https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/asset-revisioning.md). Is that relevant to what you are looking for? It should be fairly straightforward to adapt that recipe to the gulp task in this generator.

**Comment by carlosagsmendes** [comment]
Thank you @neelabhg. We ended up adopting JSPM for client side package management and we created our own strategy for asset revisioning since we also bundling dependencies. But this may be useful

**Comment by neelabhg** [comment]
Thanks for letting me know!
